### ISSUE TITLE
rpm-ostree can't consume Image built with cosa/podman4.2.0 

### ISSUE THREAD

**Issue by jmarrero** [jmarrero/atomic-setup#1]
Looks like building my dockerfile using quay.io/coreos-assembler/coreos-assembler:latest which at the moment has podman 4.2.0 causes the final image to not be able to be used by rpm-ostree:

```
rpm-ostree rebase --experimental ostree-unverified-registry:quay.io/jmarrero_rh/my-custom-fcos:silverblue-1
Pulling manifest: ostree-unverified-image:docker://quay.io/jmarrero_rh/my-custom-fcos:silverblue-1
Importing: ostree-unverified-image:docker://quay.io/jmarrero_rh/my-custom-fcos:silverblue-1 (digest: sha256:33f15bcdd428eb786d34c33d148e7b680b5566fe5fd1f42bf5bd29993ba6a862)
ostree chunk layers stored: 65 needed: 0 (0 bytes)
custom layers stored: 1 needed: 1 (334.6 MB)
Fetching layer sha256:82cffdd9305f (334.6 MB)
error: Parsing layer blob sha256:82cffdd9305f339b0b490212f261c594ac96b1b13cd76cb7f795def9e208047b: Failed to commit tar: ExitStatus(unix_wait_status(256)): error: ostree-tar: Processing deferred hardlink sysroot/ostree/repo/objects/ea/6b004bc150b3b37d623348c7b77b3486d388f64c3f1138a021b8140d267d0e.file: Failed to find object: No such file or directory: sysroot
````

If I build the same Dockerfile locally with podman 4.2.1 on Silverblue 37 it works as expected.

I thought it was building it with workflows and pushing to ghcr but building on the cosa container and pushing to quay locally results with the same error.

**Comment by jmarrero** [comment]
Looks like: https://github.com/coreos/rpm-ostree/issues/3827

**Comment by jmarrero** [comment]
Need to see if just updating podman on COSA makes it all work. Or if I can reproduce on other systems running podman 4.2.0

**Comment by cgwalters** [comment]
What's the version of rpm-ostree you're using to rebase from on the target system?

**Comment by jmarrero** [comment]
> What's the version of rpm-ostree you're using to rebase from on the target system?

rpm-ostree:
 Version: '2022.13'
 Git: 4065d4d8652fbfb975a697e3068036ecfe207166

**Comment by jmarrero** [comment]
rebuilt using COSA+podman next
```
podman version 4.4.0-dev
```
and it still gets me this failure. 

However a local build pushed to quay still works. Same Dockerfile, same host system. Something magical is happening inside cosa.

**Comment by jmarrero** [comment]
Not COSA. Using redhat's actions for buildah gives me the same issue.

```
name: Build
on:
  schedule:
  #build every 7th day of each month at 23:30
    - cron: "30 23 7 * *"
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "jmarrero-silverblue"
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}


jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with:
          context: "."
          containerfiles: Dockerfile
          image: ${{ env.IMAGE_NAME }}
          layers: false
          oci: true

      - name: Push To Registry
        uses: redhat-actions/push-to-registry@v2.6
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: "latest"
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust
```

Then on host:

```
➜  ~ rpm-ostree rebase --experimental ostree-unverified-registry:ghcr.io/jmarrero/jmarrero-silverblue:latest    
Pulling manifest: ostree-unverified-image:docker://ghcr.io/jmarrero/jmarrero-silverblue:latest
Importing: ostree-unverified-image:docker://ghcr.io/jmarrero/jmarrero-silverblue:latest (digest: sha256:c44b49d934ddef4d16ce40afeabea6051ed29e07a3cbe05899c90003f6441067)
ostree chunk layers stored: 65 needed: 0 (0 bytes)
custom layers stored: 0 needed: 1 (325.4 MB)
Fetching layer sha256:e45e6086c2cb (325.4 MB)
error: Parsing layer blob sha256:e45e6086c2cb2142bce2f9c5793ad708110be82f289e61d6e8afd5d2b1498d3f: Failed to commit tar: ExitStatus(unix_wait_status(256)): error: ostree-tar: Processing deferred hardlink sysroot/ostree/repo/objects/ea/6b004bc150b3b37d623348c7b77b3486d388f64c3f1138a021b8140d267d0e.file: Failed to find object: No such file or directory: sysroot

```
